### ISSUE TITLE
Eficiencia de código

### ISSUE THREAD

**Issue by ltejadal** [optimizacion-2-2021-1-gh-classroom/practica-2-segunda-parte-ltejadal#2]
- [x] Proponer una forma más eficiente para el método solve_tsp teniendo en cuenta el perfilamiento. 
- [x] Incluir la propuesta funcionando en los scripts la implementación.

**Comment by C1587S** [comment]
En el [notebook](https://github.com/optimizacion-2-2021-1-gh-classroom/practica-2-segunda-parte-ltejadal/blob/main/notebooks/eficiencia_codigo/reimplementacion_multiprocessing.ipynb) se incluye la propuesta para utilizar un pool de workers que computan el recorrido de un número distribuido de hormigas. 

Se propuso una reimplementación de la clase `colony`, por `colony_multiw`. Aún falta incluir esta implementación en los _scripts_ de la librería `ACO-TSP`.

Las primeras pruebas arrojan una mejora en la velocidad del tiempo de cómputo del ḿetodo `solve_tsp`.
