### ISSUE TITLE
Documentación

### ISSUE THREAD

**Issue by ltejadal** [optimizacion-2-2021-1-gh-classroom/practica-2-segunda-parte-ltejadal#3]
- [x] Corregir ligas de Kale y Kubeflow
- [x] Corregir ligas en índices y tablas

**Comment by C1587S** [comment]
Se actualizaron las ligas de jkale y Kubeflow en el commit 4de5e0c del repo donde está lalibrería. Específicamente se corrigió: https://github.com/optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-ltejadal/blob/main/src/docs/docker_images.rst

**Comment by C1587S** [comment]
- [x] Incluir documentación con nuevas funciones y clase

**Comment by C1587S** [comment]
Se corrigió la compilación de índices y tablas en el commit -m "91bc1a7" del [repo](https://github.com/optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-ltejadal) que contiene la librería.

En resumen:

Se removieron archivos `.rst` que ya no son necesarios:
-  `src/ant_colony/docs/clases.rst` 
-  `src/ant_colony/docs/functions_autosummary.rst`

Se actualizó `src/ant_colony/docs/index.rst`  dado el cambio anterior. 

Ahora los `.rst` necesarios son generados con el comando `sphinx-apidoc -o . ../ant_colony`, lo cual es incluido en el
[`github action`](https://github.com/optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-ltejadal/blob/main/.github/workflows/sphinx-doc.yml) correspondiente.
